function createAutoGeneratedNumber(field, capturedData, sanitizeForId, fieldStoredValue) {
    const fieldDiv = document.createElement('div');
    fieldDiv.className = 'form-field';

    const sanitizedId = sanitizeForId(field.control_number) + "_response";
    const label = document.createElement('label');
    label.textContent = field._control_number + ' - ' + field.jkName + ' (' + field.requirement_control_number + ')';
    const span = document.createElement('span');
    span.className = 'auto-generated-label';

    // Use existing value or generate a new one
    const uniqueId = capturedData[field.control_number] || Date.now() + '_' + Math.floor(Math.random() * 1000);
    span.textContent = uniqueId;
    fieldDiv.appendChild(label);
    fieldDiv.appendChild(span);
    capturedData[sanitizedId] = uniqueId; // Update the captured data object

    return fieldDiv;
}
