/**
 * Finds the correct rendering function based on the field's type.
 * @param {string} fieldType - The FieldType from the JSON data.
 * @returns {Function|null} The function to render the field, or null if not found.
 */
function getFieldHandler(fieldType) {
    if (!fieldType) return null;

    // Map of exact field types to their handler functions
    const exactMatchHandlers = {
        'Auto generated number': createAutoGeneratedNumber,
        'TextBox': createTextBox,
        'Decision': createDecisionField,
        'Label':createDisabledLabel,
    };

    if (exactMatchHandlers[fieldType]) {
        return exactMatchHandlers[fieldType];
    }

    // Handle types that have dynamic parts
    if (fieldType.startsWith('Dropdown box with values')) return createDropdown;
    if (fieldType.startsWith('Option box with values')) return createOptionBox;
    
    return null; // No handler found
}
