function createAutoGeneratedNumber(field, capturedData) {
    const fieldDiv = document.createElement('div');
    fieldDiv.className = 'form-field';

    const label = document.createElement('label');
    label.textContent = field.FieldLabel + ': ';
    const span = document.createElement('span');
    span.className = 'auto-generated-label';

    // Use existing value or generate a new one
    const uniqueId = capturedData[field.FieldName] || 'AutoGen_' + Date.now() + '_' + Math.floor(Math.random() * 1000);
    span.textContent = uniqueId;
    fieldDiv.appendChild(label);
    fieldDiv.appendChild(span);
    capturedData[field.FieldName] = uniqueId; // Update the captured data object

    return fieldDiv;
}