/**
 * Finds the correct rendering function based on the field's type.
 * @param {string} fieldType - The FieldType from the JSON data.
 * @returns {Function|null} The function to render the field, or null if not found
 */
function getFieldHandler(fieldType) {
    if (!fieldType) return null;

    // Map of exact field types to their handler functions
    const exactMatchHandlers = {
        'Auto generated number': createAutoGeneratedNumber,
        'TextBox': createTextBox,
        'Label':createDisabledLabel,
        'risk':createRisk,
        'objective':createObjective,
        'plan':createPlan,
        'fieldGroup':createFieldGroup,
        'comply':createComplyField,
        'mindmap': createMindMap,
        'requirement':createRequirement,
    };
    
    if (exactMatchHandlers[fieldType]) {
        return exactMatchHandlers[fieldType];
    }

    // Handle types that have dynamic parts
    if (fieldType.startsWith('Dropdown box with values')) return createDropdown;
    if (fieldType.startsWith('Option box with values')) return createOptionBox;
    if (fieldType.startsWith('Decision')) return createDecisionField;
    if (fieldType.startsWith('MultiSelect')) return createMultiSelect;

    return null; // No handler found
}
