/**
 * Creates an auto-generated number field, reusing an existing value or generating a new unique ID.
 * @param {Object} field - The field definition object from the template
 * @param {Object} capturedData - The captured data object; the generated value is written into it
 * @param {Function} sanitizeForId - Utility function to create safe HTML IDs
 * @param {Function} fieldStoredValue - Utility function to retrieve stored field values
 * @param {Object|null} [mindmap=null] - Optional mindmap data (unused, included for handler signature consistency)
 * @returns {HTMLElement} The fully constructed div element for the auto-generated number field
 */
function createAutoGeneratedNumber(field, capturedData, sanitizeForId, fieldStoredValue, mindmap = null) {
    const fieldDiv = document.createElement('div');
    fieldDiv.className = 'form-field';

    const sanitizedId = sanitizeForId(field.control_number) + "_response";
    const label = document.createElement('label');
    label.textContent = field._control_number + ' - ' + field.jkName + ' (' + field.requirement_control_number + ')';
    const span = document.createElement('span');
    span.className = 'auto-generated-label';

    // Use existing value or generate a new one
    const uniqueId = capturedData[field.control_number] || Date.now() + '_' + Math.floor(Math.random() * 1000);
    span.textContent = uniqueId;
    fieldDiv.appendChild(label);
    fieldDiv.appendChild(span);
    capturedData[sanitizedId] = uniqueId; // Update the captured data object

    return fieldDiv;
}
